### ISSUE TITLE
Any hints on getting CAN bus "on_frame" to work?

### ISSUE THREAD

**Issue by Jalle19** [leodesigner/esphome-emerson-vertiv-r48#1]
I bought an MCP2515 chip, hooked it up to my ESP32 and used the following configuration (minus all the boilerplate):

```yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

canbus:
  - platform: mcp2515
    use_extended_id: true
    cs_pin: GPIO5
    can_id: 0x0607FF83
    bit_rate: 125kbps
    mode: NORMAL
    on_frame:
    - can_id: 0x0707F803
      use_extended_id: true
      then:
      - lambda: |-
          std::string b(x.begin(), x.end());
          ESP_LOGD(">>> canbus:", "%s", &b[0] );
    - can_id: 0x060F8007
      use_extended_id: true
      then:
      - lambda: |-
          std::string b(x.begin(), x.end());
          ESP_LOGD(">>> canbus:", "%s", &b[0] );
```

The setup looks okay in the logs, but it's like I'm not receiving any frames at all. Do you have any pointers? Do I need to add a jumper on the board to terminate the bus?
